"""Atomic control state and Markdown projections."""

from __future__ import annotations

import contextlib
import datetime as dt
import fcntl
import json
import os
from pathlib import Path
import tempfile


class GoalkeeperError(Exception):
    pass


def now() -> str:
    return dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")


def atomic_text(path: Path, text: str, mode: int = 0o600) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.is_symlink():
        raise GoalkeeperError(f"Refusing symlink: {path.name}")
    fd, temporary = tempfile.mkstemp(prefix=".goalkeeper-", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as stream:
            os.fchmod(stream.fileno(), mode)
            stream.write(text)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def write_json(path: Path, value: dict) -> None:
    atomic_text(path, json.dumps(value, indent=2, ensure_ascii=False) + "\n")


def read_json(path: Path) -> dict:
    try:
        if path.stat().st_size > 2_000_000:
            raise GoalkeeperError(f"Oversized JSON file: {path.name}")
        value = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(value, dict):
            raise ValueError("expected object")
        return value
    except (OSError, ValueError) as exc:
        raise GoalkeeperError(f"Cannot read {path.name}: {exc}") from exc


def runtime(root: Path) -> Path:
    path = root / ".goalkeeper"
    if path.is_symlink():
        raise GoalkeeperError(".goalkeeper must not be a symlink")
    path.mkdir(mode=0o700, exist_ok=True)
    return path


@contextlib.contextmanager
def lock(root: Path):
    path = runtime(root) / "run.lock"
    if path.is_symlink():
        raise GoalkeeperError("run.lock must not be a symlink")
    with path.open("a+", encoding="utf-8") as stream:
        os.chmod(path, 0o600)
        try:
            fcntl.flock(stream, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError as exc:
            raise GoalkeeperError("A runner is already active for this project") from exc
        try:
            yield
        finally:
            fcntl.flock(stream, fcntl.LOCK_UN)


def initial_state(config: dict) -> dict:
    return {
        "version": 1,
        "status": "ready",
        "reason": "Not run yet",
        "updated_at": now(),
        "iterations": 0,
        "reported_tokens": 0,
        "tasks": {task["id"]: {"status": "pending", "checks": []} for task in config["tasks"]},
        "history": [],
        "runner_pid": None,
        "child_pid": None,
    }


def save_state(root: Path, state: dict, config: dict) -> None:
    state["updated_at"] = now()
    write_json(runtime(root) / "state.json", state)
    task_lines = ["# Tasks", "", "Generated by Goalkeeper; edit task definitions in goalkeeper.json.", ""]
    for task in config["tasks"]:
        current = state["tasks"].get(task["id"], {})
        passed = current.get("status") == "passed"
        task_lines.append(f"- [{'x' if passed else ' '}] {task['id']}: {task['description']}")
        for check in current.get("checks", []):
            task_lines.append(f"  - {check['status']}: `{check['command_display']}` — {check['summary']}")
    atomic_text(root / "Tasks.md", "\n".join(task_lines) + "\n")
    progress = ["# Progress", "", f"**Status:** {state['status']}", f"**Reason:** {state['reason']}",
                f"**Updated:** {state['updated_at']}", f"**Total agent iterations:** {state['iterations']}",
                f"**Reported input + output tokens:** {state['reported_tokens']}", "",
                "Token counts are reported after each turn, not a hard spending cap.", "", "## History", ""]
    pending = [task['id'] for task in config['tasks'] if state['tasks'].get(task['id'], {}).get('status') != 'passed']
    progress.insert(6, "**Next pending task:** " + (pending[0] if pending else "None; all task checks passed"))
    for entry in state["history"][-100:]:
        progress.append(f"- {entry['at']} — {entry['message']}")
    atomic_text(root / "Progress.md", "\n".join(progress) + "\n")


def event(state: dict, message: str) -> None:
    state["history"].append({"at": now(), "message": message})
    state["history"] = state["history"][-500:]
